#!/bin/bash
#######################################################
### Das Skript erstellt einen SVWS-Docker-Container ###
#######################################################
#  
# Copyright (c) $(date +%Y)
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#######################################################

# Standardwerte initialisieren
FOLDER=""
PASSWORD=""
FQDN=""
PORTNUMBER="8443"
SVWSVERSION=""
TESTDB_SQLITE="https://github.com/SVWS-NRW/SVWS-TestMDBs/raw/refs/heads/main/GOST_Abitur/Abi-Test-Daten-04/Gym_22_23_1.sqlite"


usage() {
    echo "Benutzung: $0 -o <FOLDER> -v <SVWSVERSION> [-p <PASSWORD>] [-dn <FQDN>] [-pt <PORTNUMBER>]"
    echo "  -o  Ordnerpfad (Pflichtangabe)"
    echo "  -v  SVWS Server Version (Pflichtangabe)"
    echo "  -p  Passwort (optional, sonst Autogenerierung)"
    echo "  -dn Fully Qualified Domain Name (Fallback: Ordnername)"
    echo "  -pt Portnummer (Standard: 8443)"
    exit 1
}

# Parameter verarbeiten
while [[ $# -gt 0 ]]; do
    case $1 in
        -o) FOLDER="$2"; shift 2 ;;
        -v) SVWSVERSION="$2"; shift 2 ;;
        -p) PASSWORD="$2"; shift 2 ;;
        -dn) FQDN="$2"; shift 2 ;;
        -pt) PORTNUMBER="$2"; shift 2 ;;
        *) usage ;;
    esac
done


# Installation von Docker

## locales auf de setzen
apt update
apt install -y locales
sed -i '/^# de_DE.UTF-8 UTF-8/s/^# //' /etc/locale.gen
locale-gen
update-locale LANG=de_DE.UTF-8
export LANG=de_DE.UTF-8
export LC_ALL=de_DE.UTF-8

## updaten
apt upgrade -y
apt autoremove -y

## Add Docker's official GPG key:
apt install -y ca-certificates curl nmap 
install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
chmod a+r /etc/apt/keyrings/docker.asc

## Add the repository to Apt sources:
tee /etc/apt/sources.list.d/docker.sources <<EOF
Types: deb
URIs: https://download.docker.com/linux/debian
Suites: $(. /etc/os-release && echo "$VERSION_CODENAME")
Components: stable
Signed-By: /etc/apt/keyrings/docker.asc
EOF

apt update
apt install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin nmap net-tools curl zip



# 1. Pflichtangaben prüfen
if [[ -z "$FOLDER" ]] || [[ -z "$SVWSVERSION" ]]; then
    echo "Fehler: Die Parameter -o (FOLDER) und -v (SVWSVERSION) sind zwingend erforderlich."
    usage
fi

# 2. Port-Check
if command -v lsof >/dev/null 2>&1; then
    if lsof -Pi :"$PORTNUMBER" -sTCP:LISTEN -t >/dev/null ; then
        echo "FEHLER: Port $PORTNUMBER wird bereits verwendet!"
        exit 1
    fi
fi

# 3. Fallbacks
[[ -z "$FQDN" ]] && FQDN="$FOLDER"

if [[ -z "$PASSWORD" ]]; then
    PASSWORD=$(openssl rand -base64 12)
    IS_AUTOGENERATED=true
fi


# 4. Verzeichnisstruktur vorbereiten
mkdir -p "$FOLDER/volume/mariadb"
mkdir -p "$FOLDER/volume/svws"
# Berechtigungen sicherstellen, damit MariaDB schreiben darf
chmod -R 777 "$FOLDER/volume"

# 5. .env Datei erzeugen
cat <<EOF > "$FOLDER/.env"
IMPORT_TEST_DATA=false
MARIADB_ROOT_PASSWORD=$PASSWORD
MYSQL_ROOT_PASSWORD=$PASSWORD
MARIADB_HOST=mariadb
SVWS_TLS_KEYSTORE_PASSWORD=$PASSWORD
SVWS_TLS_KEY_ALIAS=svws
SVWS_TLS_KEYSTORE_PATH=.
SVWS_TLS_CERT_CN=SVWSTESTSERVER
SVWS_TLS_CERT_OU=SVWSOU
SVWS_TLS_CERT_O=SVWSO
SVWS_TLS_CERT_L=D
SVWS_TLS_CERT_S=NRW
SVWS_TLS_CERT_C=DE
SERVERNAME=$FQDN
PORT=$PORTNUMBER
EOF

# 6. docker-compose.yml erzeugen
cat <<EOF > "$FOLDER/docker-compose.yml"
services:
  mariadb:
    restart: always
    image: mariadb:latest
    container_name: ${FQDN}_mariadb
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h localhost -u root -p${PASSWORD}"]
      start_period: 20s
      interval: 5s
      timeout: 5s
      retries: 3
    volumes:
      - ./volume/mariadb:/var/lib/mysql

  svws-server:
    image: svwsnrw/svws-server:$SVWSVERSION
    depends_on:
      mariadb:
        condition: service_healthy
    container_name: $FQDN
    ports:
      - "$PORTNUMBER:8443"
    volumes:
      - ./volume/svws:/opt/app/svws/conf
    env_file:
      - .env
EOF

echo "------------------------------------------------"
echo "Konfiguration erstellt!"
echo "------------------------------------------------"
echo "Ordner:        $FOLDER"
echo "Externer Port: $PORTNUMBER"
echo "Passwort:      $PASSWORD"
echo "------------------------------------------------"
echo "Starten mit: cd $FOLDER && docker compose up -d"
cd $FOLDER && docker compose up -d

# SVWS Schulunggsdatendanken holen
cd $SCRIPT_DIR
SCHEMA_USER="svwsadmin"
SCHEMA_PW=$PASSWORD
MARIADB_ROOT_PW=$PASSWORD

wget -O TestDB.sqlite ${TESTDB_SQLITE} 


CURL_CMD="curl --user \"root:${MARIADB_ROOT_PW}\" -k -s -o /dev/null -w \"%{http_code}\" \
  -X POST \"https://${SERVER_IP}:${SVWSPORTNUMBER}/api/schema/root/import/sqlite/svwsdb\" \
  -H 'accept: application/json' \
  -H 'Content-Type: multipart/form-data' \
  -F \"database=@${SCRIPT_DIR}/TestDB.sqlite\" \
  -F \"schemaUsername=${SCHEMA_USER}\" \
  -F \"schemaUserPassword=${SCHEMA_PW}\""

echo "Importiere die TestDatenbank:"
echo "${CURL_CMD}"

HTTP_CODE=$(eval "${CURL_CMD}")

